/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package datagen.ui;

import datagen.engine.Column;

/**
 *
 * @author juan.garson
 */
public class ColumnTab extends Tab {
    private Column data;

    /**
     * Creates new form ColumnTab
     */
    public ColumnTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        autoIncrement = new javax.swing.JCheckBox();
        foreignKey = new javax.swing.JCheckBox();
        primaryKey = new javax.swing.JCheckBox();
        isNull = new javax.swing.JCheckBox();
        dataType = new javax.swing.JLabel();
        referencePanel = new javax.swing.JPanel();
        referenceTable = new javax.swing.JLabel();
        referenceColumn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        referenceOrigin = new javax.swing.JTextField();
        referenceDest = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        autoIncPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        autoIncPivot = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(834, 466));
        setPreferredSize(new java.awt.Dimension(834, 466));

        name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        name.setText("Nombre");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion general"));

        autoIncrement.setText("AutoIncremental");
        autoIncrement.setEnabled(false);

        foreignKey.setText("Llave foranea");
        foreignKey.setEnabled(false);

        primaryKey.setText("Llave primaria");
        primaryKey.setEnabled(false);

        isNull.setText("Nuleable");
        isNull.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoIncrement)
                    .addComponent(isNull))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foreignKey)
                    .addComponent(primaryKey))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoIncrement)
                    .addComponent(primaryKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foreignKey)
                    .addComponent(isNull))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dataType.setText("Tipo de dato");

        referencePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de referencia"));

        referenceTable.setText("No existe ninguna referencia");

        referenceColumn.setText("No existe ninguna referencia");

        jLabel2.setText("Multiplicidad");

        jLabel3.setText("a");

        javax.swing.GroupLayout referencePanelLayout = new javax.swing.GroupLayout(referencePanel);
        referencePanel.setLayout(referencePanelLayout);
        referencePanelLayout.setHorizontalGroup(
            referencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(referencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(referencePanelLayout.createSequentialGroup()
                        .addComponent(referenceTable)
                        .addGap(20, 20, 20)
                        .addComponent(referenceColumn))
                    .addComponent(jLabel2)
                    .addGroup(referencePanelLayout.createSequentialGroup()
                        .addComponent(referenceOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(referenceDest, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        referencePanelLayout.setVerticalGroup(
            referencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(referencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceTable)
                    .addComponent(referenceColumn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(referencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referenceDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios"));

        jLabel1.setText("Inicio de la autonumeracion:");

        autoIncPivot.setText("0");

        javax.swing.GroupLayout autoIncPanelLayout = new javax.swing.GroupLayout(autoIncPanel);
        autoIncPanel.setLayout(autoIncPanelLayout);
        autoIncPanelLayout.setHorizontalGroup(
            autoIncPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoIncPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoIncPivot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        autoIncPanelLayout.setVerticalGroup(
            autoIncPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autoIncPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(autoIncPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(autoIncPivot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(autoIncPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(autoIncPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(referencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataType)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(dataType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(referencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel autoIncPanel;
    private javax.swing.JTextField autoIncPivot;
    private javax.swing.JCheckBox autoIncrement;
    private javax.swing.JLabel dataType;
    private javax.swing.JCheckBox foreignKey;
    private javax.swing.JCheckBox isNull;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel name;
    private javax.swing.JCheckBox primaryKey;
    private javax.swing.JLabel referenceColumn;
    private javax.swing.JTextField referenceDest;
    private javax.swing.JTextField referenceOrigin;
    private javax.swing.JPanel referencePanel;
    private javax.swing.JLabel referenceTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refreshContent(Object node) {
        try{
            save();
            
            this.data = (Column)node;
            
            name.setText(">> "+data.field);
            dataType.setText(data.typeName);
            primaryKey.setSelected(data.primaryKey);
            foreignKey.setSelected(data.foreignKey);
            isNull.setSelected(data.nullable);
            autoIncrement.setSelected(data.autoIncrement);
            
            init();
        }catch(Exception e){
            
        }    
    }
    
    private void init(){
        autoIncPanel.setVisible(false);
        referencePanel.setVisible(false);
        
        if(data.autoIncrement){
            autoIncPanel.setVisible(true);
            if(!data.getOptions().containsKey(Column.PIVOT)){
                data.getOptions().put(Column.PIVOT, 0);
            }
            autoIncPivot.setText(data.getOptions().get(Column.PIVOT).toString());
        }
        
        if(data.foreignKey){
            referencePanel.setVisible(true);
            if(!data.getOptions().containsKey(Column.REF_ORIGIN)){
                data.getOptions().put(Column.REF_ORIGIN, 1);
            }
            if(!data.getOptions().containsKey(Column.REF_DEST)){
                data.getOptions().put(Column.REF_DEST, 1);
            }
            referenceTable.setText("Columna : "+data.referenceColumn.field);
            referenceColumn.setText("Tabla : "+data.columnName);
            
            referenceOrigin.setEditable(!data.primaryKey || !data.foreignKey);
            referenceDest.setEditable(!data.primaryKey || !data.foreignKey);
            
            referenceOrigin.setText(data.getOptions().get(Column.REF_ORIGIN).toString());
            referenceDest.setText(data.getOptions().get(Column.REF_DEST).toString());
        }
    }
    
    
    private void save(){
        if(data!=null){
            if(data.autoIncrement){
                data.getOptions().put(Column.PIVOT, Integer.parseInt(autoIncPivot.getText()));
            }
        }
    }
}
